{% set name = "parsevasp" %}
{% set version = "3.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/parsevasp-{{ version }}.tar.gz
  sha256: a3925993cfe9596fdddcd3f9a0df7366598f0bb08e60ca30d17b27047c6c7d81

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - future
    - lxml
    - numpy
    - python >=3.7
    - pyyaml

test:
  imports:
    - parsevasp
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/aiida-vasp/parsevasp
  summary: A general parser for VASP
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - chrisjsewell
