{% set name = "parsevasp" %}
{% set version = "3.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/parsevasp-{{ version }}.tar.gz
  sha256: 3be1dff9b291ba97b3b1874027d8b741db43a9c8d255ce58b12c19d6cf4b98eb

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - future
    - lxml
    - numpy
    - python >=3.7
    - pyyaml

test:
  imports:
    - parsevasp
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/aiida-vasp/parsevasp
  summary: A general parser for VASP
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - chrisjsewell
